### ISSUE TITLE
Adding suffix to all resource urls

### ISSUE THREAD

**Issue by pienisieni** [get-set-fetch/extension#60]
Could it be possible to add a custom suffix to all the extracted URLs?

So that if for example the selector "a.question_link" would extract the following URLs:

```
https://www.question.com/link/Question-1
https://www.question.com/link/Question-2
https://www.question.com/link/Question-3
https://www.question.com/link/Question-4
```

They would be automatically suffixed for extracting HTML content from these URLs:

```
https://www.question.com/link/Question-1/log
https://www.question.com/link/Question-2/log
https://www.question.com/link/Question-3/log
https://www.question.com/link/Question-4/log
```

Thank you.

**Comment by a1sabau** [comment]
Since this seems related to #59 as it was opened at the same time, I'm looking at solutions related to ExtractHtmlContentPlugin. 

The more "elegant" solution would be to add a new plugin modifying the scraped content after the ExtractHtmlContentPlugin but that involves creating a new scenario, something that you can't do from the UI atm.

The "simple" solution would be to modify the ExtractHtmlContentPlugin code by editing the plugin from the "Plugins" menu entry. Within the code section, look for the following line:

```js
const content = this.extractContent();
```

Below it add:

```js
Object.keys(content).forEach(key => {
	if (/href/.test(key) && content[key])  {
		content[key] = content[key].map(hrefEntry => hrefEntry + "/log");
	}
});
```

This will append "/log" suffix to all content selectors that target the href property.
Warning! This applies for all scraping projects as the plugins are shared across projects.

Happy scraping :)

**Comment by pienisieni** [comment]
Wow, thank you.

Am I doing something wrong as this does not seem to be working for me (tried Firefox, Chrome).

It's still extracting HTML content from URLs without the /log suffix.

Made changes to ExtractHtmlContentPlugin:

![dashdsahdas](https://user-images.githubusercontent.com/9020358/103256191-a0d05d80-49cf-11eb-8507-e35b83941541.jpg)

Tried disabling/enabling extension/add-on, restarting browser.

![jdisajdias](https://user-images.githubusercontent.com/9020358/103256275-f9075f80-49cf-11eb-8d06-9d0de2c56247.jpg)

![sjdiashdsai](https://user-images.githubusercontent.com/9020358/103256326-366bed00-49d0-11eb-8965-0dc4f2e3f665.jpg)

**Comment by a1sabau** [comment]
The plugin changes look fine. A browser restart should enforce them.
 
My assumption was that this issue is related to #59. 
If this is the case you need to solve two problems:
- scrape all urls from the page as content. This is shown in #59 and will result in a single url entry under the results tab. That single entry will contain as content all the urls present in that page.
- modify the scraped urls. This is shown in this thread.

Using both the above you end up with a list of scraped urls from a single page that are appended with "/log".

If you need to keep scraping urls discovered from the start page but modify them prior to scraping by appending "/log" the solution I've posted will not work. You will need to modify code from ExtractUrlsPlugin in order to do that ...

**Comment by pienisieni** [comment]
> If you need to keep scraping urls discovered from the start page but modify them prior to scraping by appending "/log" the solution I've posted will not work. You will need to modify code from ExtractUrlsPlugin in order to do that ...

This is exactly what I wanted to achieve. Append the /log suffix prior to scraping them.
I apologies for the confusion.

Advice on how to modify the code from ExtractUrlsPlugin to achieve that would be hugely appreciated.

Thank you so much Andrei.

**Comment by a1sabau** [comment]
Got it. Modify ExtractUrlsPlugin by replacing:

```js
resource.url = fullUrl.toString();
```

with

```js
resource.url = fullUrl.toString() + "/logs";
```

This will append "/logs" to ALL discovered URLs regardless  of scraping project as the plugins are shared between projects !
Depending on discovered links you may end up with URLs like "mysite.com/img.png/logs".

It makes sense to add some condition and only append based on it, like:

```js
if (fullUrl.hostname === "www.mysite.com") {
   resource.url = fullUrl.toString() + "/logs";
}
else {
    resource.url = fullUrl.toString();
}

```

fullUrl is an [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL ), you can create more advanced conditions based on its properties.

Hope this helps.

**Comment by a1sabau** [comment]
Not sure how useful an ExtractUrlsPlugin.suffix option would be for most users. I think such custom modifications are better handled by modifying the plugin code as described above since the extension supports it. Closing it for now.
