### ISSUE TITLE
:has not supported?

### ISSUE THREAD

**Issue by fencer** [get-set-fetch/extension#76]
When using the selector `li:has(> span.current) ~ li:first()` a the browser extension is crashing. 
[get-set-fetch.logs.csv](https://github.com/get-set-fetch/extension/files/7306311/get-set-fetch.logs.csv)

**Comment by a1sabau** [comment]
Running in browser console 
`document.querySelectorAll('li:has(> span.current) ~ li:first()')`
returns 'not a valid selector error'. So it doesn't work in browser either.

According to [mozilla :has page](https://developer.mozilla.org/en-US/docs/Web/CSS/:has), no browser supports :has at the moment. Removing the :has selector, there's still an error on `:first()`, you probably want `:first-child`.

Closing it due to no browser support for :has.
